apm install advanced-open-file
apm install eol-enforcer
apm install language-postcss
apm install linter
apm install linter-eslint
apm install linter-htmlhint
apm install linter-stylelint
apm install minimap
apm install pretty-json
